version: '3.3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
    ports:
      - 5435:5435
    command: -p 5435

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finance

  redis:
    image: redis
    ports:
      - 6380:6380
    command: --port 6380
    networks:
      - finance
    volumes:
      - redisdata:/data
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - '3001:80'

    restart: on-failure

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      DB_HOST: postgres
      DB_PORT: 5435
      REDIS_URL: redis://redis:6380
    networks:
      - finance
    restart: on-failure

volumes:
  redisdata:
    driver: local
  pgdata:
networks:
  finance:
    driver: bridge
