const translateMessage: object = {
  'invalid name': 'نام معتبر نیست',
  'invalid price': 'مبلغ معتبر نیست',
  'invalid amount': 'تعداد معتبر نیست',
  'invalid limit': 'limit معتبر نیست',
  'invalid offset': 'offset معتبر نیست',
  'invalid product id': 'شناسه محصول معتبر نیست',
  'product with this name already exist': 'نام محصول تکراری است',
  'error happened': 'خطایی رخ داده است',
  'product is already deleted': 'محصول قبلا حذف شده است',
  'product not found': 'محصولی یافت نشد',
  'invoice not found': 'فاکتور یافت نشد',
  'no invoice found for this product': 'فاکتوری برای این محصول یافت نشد',
  'invalid id': 'شناسه ارسالی معتبر نیست ',
  'customer already exist with this username':
    'کاربر با این نام کاربری وجود دارد',
  'invalid password': 'رمز عبور نامعتبر است',
  'invalid username': 'نام کاربری نامعتبر است',
  'invalid user id': 'شناسه کاربر نامعتبر است',
  'invalid company': 'شناسه فروشگاه نامعتبر است',
  'company not found': 'فروشگاه یافت نشد',
  'invalid company name': 'نام فروشگاه نامعتبر است',
  'company already exist with this name': 'فروشگاه با این نام وجود دارد',
  'invalid role': 'دسترسی کاربر نامعتبر است',
  'company creator must have admin role':
    'سازنده فروشگاه باید دسترسی ادمین داشته باشد',
  'no company found': 'فروشگاهی یافت نشد',
  'invalid login': 'نام کاربری یا رمز عبور نادرست است',
  'you dont have access to do this operation':
    'شما دسترسی لازم برای انجام این عملیات را ندارید',
  'invalid customer name': 'نام مشتری نامعتبر است',
  'invalid address': 'آدرس نامعتبر است',
  'invalid phone': 'شماره موبایل نامعتبر است',
  'invalid postal code': 'کد پستی نامعتبر است',
  'invalid tracking code': 'کد پیگیری مرسوله نامعتیر است',
  'invalid order date': 'تاریخ ثبت سفارش نامعتبر است',
  'invalid shipping date': 'تاریخ ارسال نامعتبر است',
  'invalid shipping price for customer':
    'هزینه ارسال پستی برای مشتری نامعتبر است',
  'invalid shipping price for seller':
    'هزینه ارسال پستی برای فروشنده نامعتبر است',
  'invalid discount': 'مبلغ تخفیف نامعتبر است',
  'invalid source of sell': 'نوع فروش نامعتبر است',
  'invalid products': 'محصولات وارد شده برای سفارش نامعتبر هستند',
  'there is no enough product in stock':
    'به اندازه کافی محصول در انبار موجود نیست',
  'order not found': 'سفارش مورد نظر یافت نشد',
  'invalid boolean': 'مقدار ورودی نامعتبر است',
  'invalid users': 'ورودی نامعتبر است',
  'user not found': 'کاربر یافت نشد',
  'invalid share percent': 'درصد سهام کاربر نامعتبر است',
  'total share percents must be 100':
    'مجموع درصد سهام کاربران باید صد درصد شود',
  'invalid checkout amount': 'مبلغ تسویه حساب نامعتبر است',
  'invalid description': 'توضیحات نامعتبر است',
  'atleast one of incomes is already settled':
    'حداقل یکی از درآمد ها قبلا تسویه حساب شده است',
  'checkout not found': 'اطلاعات تسویه حساب یافت نشد',
  'you dont have access to this data': 'شما به این اطلاعات دسترسی ندارید',
  'data not found': 'اطلاعات یافت نشد',
  'invalid input': 'ورودی نامعتبر است',
  'invalid from date': 'تاریخ شروع نامعتبر است',
  'invalid to date': 'تاریخ پایان نامعتبر است',
  'incomes of this order are already settled, can not update':
    'تسویه حساب درآمد های حاصل از این سفارش انجام شده است، امکان به روز رسانی وجود ندارد ',
  'invalid language': 'زبان نامعتبر است',
  'no income found': 'درآمدی یافت نشد',
  'no checkout found': 'تسویه حسابی یافت نشد',
  'invalid uuid': 'کد شرکت نامعتبر است',
}

export default translateMessage
